#' @title INaturalist data | Heterogeneous | 30 record
#' @description A small and heterogeneous dataset for testing
#' @format A data frame with 30 rows and 155 variables:
#' \describe{
#'   \item{\code{rightsHolder}}{character COLUMN_DESCRIPTION}
#'   \item{\code{infraphylum}}{character COLUMN_DESCRIPTION}
#'   \item{\code{country}}{character COLUMN_DESCRIPTION}
#'   \item{\code{date_year}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{scientificNameID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{individualCount}}{character COLUMN_DESCRIPTION}
#'   \item{\code{dropped}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{gigaclassid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{aphiaID}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{latitude}}{double COLUMN_DESCRIPTION}
#'   \item{\code{subclassid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{type}}{character COLUMN_DESCRIPTION}
#'   \item{\code{gigaclass}}{character COLUMN_DESCRIPTION}
#'   \item{\code{infraphylumid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{phylumid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{familyid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{catalogNumber}}{character COLUMN_DESCRIPTION}
#'   \item{\code{occurrenceStatus}}{character COLUMN_DESCRIPTION}
#'   \item{\code{basisOfRecord}}{character COLUMN_DESCRIPTION}
#'   \item{\code{terrestrial}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{id}}{character COLUMN_DESCRIPTION}
#'   \item{\code{parvphylum}}{character COLUMN_DESCRIPTION}
#'   \item{\code{order}}{character COLUMN_DESCRIPTION}
#'   \item{\code{recordNumber}}{character COLUMN_DESCRIPTION}
#'   \item{\code{dataset_id}}{character COLUMN_DESCRIPTION}
#'   \item{\code{locality}}{character COLUMN_DESCRIPTION}
#'   \item{\code{longitude}}{double COLUMN_DESCRIPTION}
#'   \item{\code{collectionCode}}{character COLUMN_DESCRIPTION}
#'   \item{\code{date_end}}{double COLUMN_DESCRIPTION}
#'   \item{\code{speciesid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{occurrenceID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{license}}{character COLUMN_DESCRIPTION}
#'   \item{\code{date_start}}{double COLUMN_DESCRIPTION}
#'   \item{\code{genus}}{character COLUMN_DESCRIPTION}
#'   \item{\code{collectionID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{eventDate}}{double COLUMN_DESCRIPTION}
#'   \item{\code{brackish}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{superorder}}{character COLUMN_DESCRIPTION}
#'   \item{\code{absence}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{subfamily}}{character COLUMN_DESCRIPTION}
#'   \item{\code{superorderid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{genusid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{originalScientificName}}{character COLUMN_DESCRIPTION}
#'   \item{\code{marine}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{subphylumid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{subfamilyid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{institutionCode}}{character COLUMN_DESCRIPTION}
#'   \item{\code{date_mid}}{double COLUMN_DESCRIPTION}
#'   \item{\code{class}}{character COLUMN_DESCRIPTION}
#'   \item{\code{orderid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{kingdom}}{character COLUMN_DESCRIPTION}
#'   \item{\code{recordedBy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{classid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{phylum}}{character COLUMN_DESCRIPTION}
#'   \item{\code{species}}{character COLUMN_DESCRIPTION}
#'   \item{\code{subphylum}}{character COLUMN_DESCRIPTION}
#'   \item{\code{subclass}}{character COLUMN_DESCRIPTION}
#'   \item{\code{family}}{character COLUMN_DESCRIPTION}
#'   \item{\code{kingdomid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{parvphylumid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{node_id}}{list COLUMN_DESCRIPTION}
#'   \item{\code{flags}}{list COLUMN_DESCRIPTION}
#'   \item{\code{sss}}{double COLUMN_DESCRIPTION}
#'   \item{\code{shoredistance}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{sst}}{double COLUMN_DESCRIPTION}
#'   \item{\code{bathymetry}}{double COLUMN_DESCRIPTION}
#'   \item{\code{year}}{character COLUMN_DESCRIPTION}
#'   \item{\code{fieldNumber}}{character COLUMN_DESCRIPTION}
#'   \item{\code{language}}{character COLUMN_DESCRIPTION}
#'   \item{\code{superclass}}{character COLUMN_DESCRIPTION}
#'   \item{\code{modified}}{character COLUMN_DESCRIPTION}
#'   \item{\code{maximumDepthInMeters}}{double COLUMN_DESCRIPTION}
#'   \item{\code{day}}{character COLUMN_DESCRIPTION}
#'   \item{\code{superclassid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{footprintSRS}}{character COLUMN_DESCRIPTION}
#'   \item{\code{month}}{character COLUMN_DESCRIPTION}
#'   \item{\code{samplingProtocol}}{character COLUMN_DESCRIPTION}
#'   \item{\code{parentEventID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{eventID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{eventRemarks}}{character COLUMN_DESCRIPTION}
#'   \item{\code{minimumDepthInMeters}}{double COLUMN_DESCRIPTION}
#'   \item{\code{preparations}}{character COLUMN_DESCRIPTION}
#'   \item{\code{infraclassid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{infraclass}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sex}}{character COLUMN_DESCRIPTION}
#'   \item{\code{datasetName}}{character COLUMN_DESCRIPTION}
#'   \item{\code{geodeticDatum}}{character COLUMN_DESCRIPTION}
#'   \item{\code{depth}}{double COLUMN_DESCRIPTION}
#'   \item{\code{lifeStage}}{character COLUMN_DESCRIPTION}
#'   \item{\code{datasetID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{institutionID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{superfamilyid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{infraorderid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{superfamily}}{character COLUMN_DESCRIPTION}
#'   \item{\code{suborderid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{scientificNameAuthorship}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxonRank}}{character COLUMN_DESCRIPTION}
#'   \item{\code{vernacularName}}{character COLUMN_DESCRIPTION}
#'   \item{\code{locationRemarks}}{character COLUMN_DESCRIPTION}
#'   \item{\code{suborder}}{character COLUMN_DESCRIPTION}
#'   \item{\code{infraorder}}{character COLUMN_DESCRIPTION}
#'   \item{\code{dataGeneralizations}}{character COLUMN_DESCRIPTION}
#'   \item{\code{specificEpithet}}{character COLUMN_DESCRIPTION}
#'   \item{\code{associatedReferences}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxonRemarks}}{character COLUMN_DESCRIPTION}
#'   \item{\code{georeferencedDate}}{character COLUMN_DESCRIPTION}
#'   \item{\code{verbatimEventDate}}{character COLUMN_DESCRIPTION}
#'   \item{\code{organismID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{dateIdentified}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ownerInstitutionCode}}{character COLUMN_DESCRIPTION}
#'   \item{\code{bibliographicCitation}}{character COLUMN_DESCRIPTION}
#'   \item{\code{coordinateUncertaintyInMeters}}{character COLUMN_DESCRIPTION}
#'   \item{\code{eventTime}}{character COLUMN_DESCRIPTION}
#'   \item{\code{identificationRemarks}}{character COLUMN_DESCRIPTION}
#'   \item{\code{nomenclaturalCode}}{character COLUMN_DESCRIPTION}
#'   \item{\code{footprintWKT}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxonomicStatus}}{character COLUMN_DESCRIPTION}
#'   \item{\code{waterBody}}{character COLUMN_DESCRIPTION}
#'   \item{\code{coordinatePrecision}}{character COLUMN_DESCRIPTION}
#'   \item{\code{organismRemarks}}{character COLUMN_DESCRIPTION}
#'   \item{\code{occurrenceRemarks}}{character COLUMN_DESCRIPTION}
#'   \item{\code{locationID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{verbatimCoordinates}}{character COLUMN_DESCRIPTION}
#'   \item{\code{category}}{character COLUMN_DESCRIPTION}
#'   \item{\code{dynamicProperties}}{character COLUMN_DESCRIPTION}
#'   \item{\code{habitat}}{character COLUMN_DESCRIPTION}
#'   \item{\code{references}}{character COLUMN_DESCRIPTION}
#'   \item{\code{minimumElevationInMeters}}{character COLUMN_DESCRIPTION}
#'   \item{\code{stateProvince}}{character COLUMN_DESCRIPTION}
#'   \item{\code{maximumElevationInMeters}}{character COLUMN_DESCRIPTION}
#'   \item{\code{samplingEffort}}{character COLUMN_DESCRIPTION}
#'   \item{\code{startDayOfYear}}{character COLUMN_DESCRIPTION}
#'   \item{\code{subkingdom}}{character COLUMN_DESCRIPTION}
#'   \item{\code{infrakingdom}}{character COLUMN_DESCRIPTION}
#'   \item{\code{subkingdomid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{infrakingdomid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{tribeid}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{tribe}}{character COLUMN_DESCRIPTION}
#'   \item{\code{municipality}}{character COLUMN_DESCRIPTION}
#'   \item{\code{countryCode}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sampleSizeUnit}}{character COLUMN_DESCRIPTION}
#'   \item{\code{georeferencedBy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{island}}{character COLUMN_DESCRIPTION}
#'   \item{\code{islandGroup}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxonID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{identifiedBy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{georeferenceProtocol}}{character COLUMN_DESCRIPTION}
#'   \item{\code{verbatimDepth}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sampleSizeValue}}{character COLUMN_DESCRIPTION}
#'   \item{\code{organismQuantity}}{character COLUMN_DESCRIPTION}
#'   \item{\code{organismQuantityType}}{character COLUMN_DESCRIPTION}
#'   \item{\code{continent}}{character COLUMN_DESCRIPTION}
#'   \item{\code{informationWithheld}}{character COLUMN_DESCRIPTION}
#'   \item{\code{prov}}{character COLUMN_DESCRIPTION}
#'}
#' @details DETAILS
"inat_30r"

#' @title INaturalist data| Heterogeneous | 10,000 record
#' @description A medium size dataset for testing
#' @format A data frame with 10000 rows and 154 variables:
#' \describe{
#'   \item{\code{quality_grade}}{character COLUMN_DESCRIPTION}
#'   \item{\code{time_observed_at}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon_geoprivacy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{annotations}}{list COLUMN_DESCRIPTION}
#'   \item{\code{uuid}}{character COLUMN_DESCRIPTION}
#'   \item{\code{id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{cached_votes_total}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{identifications_most_agree}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{species_guess}}{character COLUMN_DESCRIPTION}
#'   \item{\code{identifications_most_disagree}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{tags}}{character COLUMN_DESCRIPTION}
#'   \item{\code{positional_accuracy}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{comments_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{site_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{created_time_zone}}{character COLUMN_DESCRIPTION}
#'   \item{\code{license_code}}{character COLUMN_DESCRIPTION}
#'   \item{\code{observed_time_zone}}{character COLUMN_DESCRIPTION}
#'   \item{\code{quality_metrics}}{list COLUMN_DESCRIPTION}
#'   \item{\code{public_positional_accuracy}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{reviewed_by}}{list COLUMN_DESCRIPTION}
#'   \item{\code{oauth_application_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{flags}}{list COLUMN_DESCRIPTION}
#'   \item{\code{created_at}}{character COLUMN_DESCRIPTION}
#'   \item{\code{description}}{character COLUMN_DESCRIPTION}
#'   \item{\code{time_zone_offset}}{character COLUMN_DESCRIPTION}
#'   \item{\code{project_ids_with_curator_id}}{list COLUMN_DESCRIPTION}
#'   \item{\code{observed_on}}{double COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_string}}{character COLUMN_DESCRIPTION}
#'   \item{\code{updated_at}}{character COLUMN_DESCRIPTION}
#'   \item{\code{sounds}}{list COLUMN_DESCRIPTION}
#'   \item{\code{place_ids}}{list COLUMN_DESCRIPTION}
#'   \item{\code{captive}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{ident_taxon_ids}}{list COLUMN_DESCRIPTION}
#'   \item{\code{outlinks}}{list COLUMN_DESCRIPTION}
#'   \item{\code{faves_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{ofvs}}{list COLUMN_DESCRIPTION}
#'   \item{\code{num_identification_agreements}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{comments}}{list COLUMN_DESCRIPTION}
#'   \item{\code{map_scale}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{uri}}{character COLUMN_DESCRIPTION}
#'   \item{\code{project_ids}}{list COLUMN_DESCRIPTION}
#'   \item{\code{community_taxon_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{owners_identification_from_vision}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{identifications_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{obscured}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{num_identification_disagreements}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{geoprivacy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{location}}{character COLUMN_DESCRIPTION}
#'   \item{\code{votes}}{list COLUMN_DESCRIPTION}
#'   \item{\code{spam}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{mappable}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{identifications_some_agree}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{project_ids_without_curator_id}}{list COLUMN_DESCRIPTION}
#'   \item{\code{place_guess}}{character COLUMN_DESCRIPTION}
#'   \item{\code{identifications}}{list COLUMN_DESCRIPTION}
#'   \item{\code{project_observations}}{list COLUMN_DESCRIPTION}
#'   \item{\code{observation_sounds}}{list COLUMN_DESCRIPTION}
#'   \item{\code{photos}}{list COLUMN_DESCRIPTION}
#'   \item{\code{observation_photos}}{list COLUMN_DESCRIPTION}
#'   \item{\code{faves}}{list COLUMN_DESCRIPTION}
#'   \item{\code{non_owner_ids}}{list COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_details.date}}{character COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_details.week}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_details.month}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_details.hour}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_details.year}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{observed_on_details.day}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{created_at_details.date}}{character COLUMN_DESCRIPTION}
#'   \item{\code{created_at_details.week}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{created_at_details.month}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{created_at_details.hour}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{created_at_details.year}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{created_at_details.day}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.is_active}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.ancestry}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.min_species_ancestry}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.endemic}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.iconic_taxon_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.min_species_taxon_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.threatened}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.rank_level}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.introduced}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.native}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.parent_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.rank}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.extinct}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.ancestor_ids}}{list COLUMN_DESCRIPTION}
#'   \item{\code{taxon.photos_locked}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.taxon_schemes_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.wikipedia_url}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.current_synonymous_taxon_ids}}{list COLUMN_DESCRIPTION}
#'   \item{\code{taxon.created_at}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.taxon_changes_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.complete_species_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.universal_search_rank}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.observations_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.atlas_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.iconic_taxon_name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.preferred_common_name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.complete_rank}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.flag_counts.resolved}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.flag_counts.unresolved}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.license_code}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.attribution}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.url}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.flags}}{list COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.square_url}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.medium_url}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.original_dimensions.height}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.default_photo.original_dimensions.width}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.place_id}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.source_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.user_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.authority}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.status}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.status_name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.geoprivacy}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.iucn}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.user.id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.user.login}}{character COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.user.icon_url}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{taxon.conservation_status.user.orcid}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{preferences.prefers_community_taxon}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{geojson.coordinates}}{list COLUMN_DESCRIPTION}
#'   \item{\code{geojson.type}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.site_id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.created_at}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.id}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.login}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.spam}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{user.suspended}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{user.login_autocomplete}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.login_exact}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.name}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.name_autocomplete}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.orcid}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.icon}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.observations_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.identifications_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.journal_posts_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.activity_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.species_count}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.universal_search_rank}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{user.roles}}{list COLUMN_DESCRIPTION}
#'   \item{\code{user.icon_url}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.preferences.prefers_community_taxa}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{user.preferences.prefers_observation_fields_by}}{character COLUMN_DESCRIPTION}
#'   \item{\code{user.preferences.prefers_project_addition_by}}{character COLUMN_DESCRIPTION}
#'   \item{\code{prov}}{character COLUMN_DESCRIPTION}
#'   \item{\code{longitude}}{character COLUMN_DESCRIPTION}
#'   \item{\code{latitude}}{character COLUMN_DESCRIPTION}
#'}
#' @details DETAILS
"inat_10k"
